import os
import subprocess
import tempfile
from src.agents.state import MigrationState

def validator_node(state: MigrationState) -> MigrationState:
    """
    LangGraph Agent Node: Executes isolated syntax and test checking.
    Intercepts failures and outputs raw stack traces back into the state machine.
    """
    print("\n--- [AGENT: VALIDATOR] Running test execution loop ---")
    
    refactored_code = state.get("refactored_code")
    if not refactored_code:
        print("[VALIDATOR ERROR] No code was generated by the Refactorer.")
        return {**state, "validation_errors": "Refactored code is empty."}

    # Write code to a secure temporary execution file for testing
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False, mode="w") as temp_file:
        temp_file.write(refactored_code)
        temp_file_path = temp_file.name

    try:
        print(f"[VALIDATOR] Executing syntax and baseline compilation checks on candidate...")
        # Use subprocess to run python syntax compilation check
        result = subprocess.run(
            ["python", "-m", "py_compile", temp_file_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=5
        )
        
        if result.returncode != 0:
            print("[VALIDATOR FAILURE] Syntax error or compilation failure detected.")
            # Sanitize the absolute path out of the stack trace to keep logs clean
            error_trace = result.stderr.replace(temp_file_path, "app.py")
            return {
                **state,
                "validation_errors": error_trace
            }
            
        print("[VALIDATOR SUCCESS] Upgraded code passed all syntax verification checks.")
        return {
            **state,
            "validation_errors": None
        }

    except Exception as e:
        print(f"[VALIDATOR EXCEPTION] Target validation runtime crashed: {e}")
        return {**state, "validation_errors": str(e)}
        
    finally:
        # Secure file system cleanup
        if os.path.exists(temp_file_path):
            os.remove(temp_file_path)
