import ast
import os
import subprocess
import tempfile
from src.agents.state import MigrationState

_ROUTE_METHODS = {"get", "post", "put", "delete", "patch", "route"}
_SYNC_HTTP_METHODS = {"get", "post", "put", "delete", "patch"}


def _collect_imports(tree: ast.AST) -> tuple[set, set]:
    """Returns (imported_modules, imported_names) from the AST."""
    modules, names = set(), set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                modules.add(alias.name)
        elif isinstance(node, ast.ImportFrom) and node.module:
            modules.add(node.module)
            for alias in node.names:
                names.add(alias.name)
    return modules, names


def _check_import_issues(modules: set, names: set) -> list[str]:
    issues = []
    if "fastapi" not in modules and "FastAPI" not in names:
        issues.append("FastAPI is not imported — migration appears incomplete.")
    if any(m == "flask" or m.startswith("flask.") for m in modules):
        issues.append("Flask is still imported — migration incomplete.")
    return issues


def _check_call_issues(tree: ast.AST) -> list[str]:
    issues = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        func = node.func
        caller = getattr(func.value, "id", None)
        if func.attr == "sleep" and caller == "time":
            issues.append(
                f"Line {node.lineno}: Unmigrated 'time.sleep()' still present — should be 'await asyncio.sleep()'."
            )
        if func.attr in _SYNC_HTTP_METHODS and caller == "requests":
            issues.append(
                f"Line {node.lineno}: Unmigrated 'requests.{func.attr}()' still present — should use httpx.AsyncClient."
            )
    return issues


def _check_async_route_issues(tree: ast.AST) -> list[str]:
    issues = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        for decorator in node.decorator_list:
            attr = None
            if isinstance(decorator, ast.Attribute):
                attr = decorator.attr
            elif isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute):
                attr = decorator.func.attr
            if attr in _ROUTE_METHODS:
                issues.append(
                    f"Line {node.lineno}: Route handler '{node.name}' is not declared as 'async def'."
                )
                break
    return issues


def _check_migration_quality(code: str) -> list[str]:
    """
    Parses the refactored code and checks for common migration failures.
    Returns a list of problem descriptions, empty if the output looks correct.
    """
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return [f"Output has a syntax error: {e.msg} at line {e.lineno}"]

    modules, names = _collect_imports(tree)
    return (
        _check_import_issues(modules, names) +
        _check_call_issues(tree) +
        _check_async_route_issues(tree)
    )


def validator_node(state: MigrationState) -> MigrationState:
    """
    LangGraph Agent Node: Two-stage validation.
    Stage 1 — py_compile syntax check.
    Stage 2 — AST analysis of the output for migration completeness.
    """
    print("\n--- [AGENT: VALIDATOR] Running validation checks ---")

    refactored_code = state.get("refactored_code")
    if not refactored_code:
        print("[VALIDATOR ERROR] No code was generated by the Refactorer.")
        return {**state, "validation_errors": "Refactored code is empty."}

    with tempfile.NamedTemporaryFile(suffix=".py", delete=False, mode="w") as temp_file:
        temp_file.write(refactored_code)
        temp_file_path = temp_file.name

    try:
        # Stage 1: syntax check
        print("[VALIDATOR] Stage 1: syntax check...")
        result = subprocess.run(
            ["python", "-m", "py_compile", temp_file_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=5
        )

        if result.returncode != 0:
            print("[VALIDATOR FAILURE] Syntax error detected.")
            error_trace = result.stderr.replace(temp_file_path, "app.py")
            return {**state, "validation_errors": error_trace}

        # Stage 2: migration quality check
        print("[VALIDATOR] Stage 2: migration quality check...")
        issues = _check_migration_quality(refactored_code)

        if issues:
            print(f"[VALIDATOR FAILURE] {len(issues)} migration issue(s) detected.")
            error_trace = "\n".join(f"- {i}" for i in issues)
            return {**state, "validation_errors": error_trace}

        print("[VALIDATOR SUCCESS] Passed syntax and migration quality checks.")
        return {**state, "validation_errors": None}

    except Exception as e:
        print(f"[VALIDATOR EXCEPTION] Validation crashed: {e}")
        return {**state, "validation_errors": str(e)}

    finally:
        if os.path.exists(temp_file_path):
            os.remove(temp_file_path)
